### ISSUE TITLE
_EagerConst: Dst tensor is not initialized

### ISSUE THREAD

**Issue by sonjajovic** [chenhcs/SCS#1]
Hello everyone, 

I am trying your method for cell segmentation, but I run into an error.
I created conda environment according to the stated requirements  (**python 3.9.7,  tensorflow 2.8.2, tensorflow_addons 0.16.1)**  
The first time I try to run it on AWS EC2 instance **g5.12xlarge**, and I didn't provide drivers for the graphic card (by mistake), so the method used only CPU, and the analysis of provided data lasted about 5h and finished successfully. 

After installing the driver with the following specifications 

 `| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0  |`
 
I got this error 

> 2023-03-13 13:04:29.448979: W tensorflow/core/common_runtime/bfc_allocator.cc:474]********************************************______________________________________________________
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/scs_data/SCS_orig/SCS/main.py", line 19, in <module>
>     transformer.train()
>   File "/home/ubuntu/scs_data/SCS_orig/SCS/src/transformer.py", line 231, in train
>     run_experiment(transformer_classifier, x_train, x_train_pos, x_train_, x_train_pos_, y_train, y_train_, y_binary_train, x_test, x_test_pos, x_validation, x_validation_pos, y_validation, y_binary_validation, learning_rate, weight_decay, batch_size, num_epochs)
>   File "/home/ubuntu/scs_data/SCS_orig/SCS/src/transformer.py", line 139, in run_experiment
>     pred_centers_test, pred_binary_test = model.predict(x = [x_test, x_test_pos], batch_size=batch_size)
>   File "/home/ubuntu/miniconda3/envs/scs_env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
>     raise e.with_traceback(filtered_tb) from None
>   File "/home/ubuntu/miniconda3/envs/scs_env/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 102, in convert_to_eager_tensor
>     return ops.EagerTensor(value, ctx.device_name, dtype)
> tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.     
 
I understood that the problem is with the GPU memory and found several solutions for the mentioned problem on the Internet, for example reducing the batch size, but the error appears again. 

Also, I saw that you imported the **gc** (garbage collector)module, do I need to run` gc. collect()` somewhere in the code?
I just wanted to ask if you might have encountered the same or a similar problem and how did you solve it?  

Thank you in advance for any help!

**Comment by chenhcs** [comment]
Hi, I think this issue is due to running out of GPU memory. We observed this error in newer TF versions although older TF versions work well on the same GPU card. We have updated the code in the inference part to make predictions by batches to address this issue. Please check out our latest code.
